const PHOTO_LIST = [

  'images/baokhoi.jpg',
  'images/cumanhdat.jpg',
  'images/duyanh.jpg',
  'images/gv_KTD.jpg',
  'images/hnav.jpg',
  'images/hoanganh.jpg',
  'images/huyentrang.jpg',
  'images/lehang.jpg',
  'images/lethanhthao.jpg',
  'images/luutunglam.jpg',
  'images/ndmd.jpg',
  'images/ngodoandat.jfif',
  'images/nguyenanh.jpg',
  'images/nguyenchien.jpg',
  'images/nguyendung.png',
  'images/nguyenhoa.jpg',
  'images/nguyenhongson.jpg',
  'images/nguyenhue.png',
  'images/nguyenhung.jpg',
  'images/nguyenlinh.jpg',
  'images/nguyenloan.jpg',
  'images/nguyenngoc.jpg',
];
